apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kibana.fullname" . }}
  labels:
    app: {{ template "kibana.name" . }}
    chart: {{ template "kibana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  plugins: |
{{- range $plugin := .Values.plugins }}
    {{ $plugin }}
{{- end }}
  launch_kibana: |
    #!/usr/bin/env bash
    set -euf -o pipefail
    if [[ -f /tmp/plugins ]]; then
      while read plugin; do
        echo "Installing plugin: ${plugin}"
        /usr/share/kibana/bin/kibana-plugin install "${plugin}"
      done < /tmp/plugins
    fi
    /usr/local/bin/kibana-docker "$@"
{{- range $key, $value := .Values.configFiles }}
  {{ $key }}: |
{{ toYaml $value | default "{}" | indent 4 }}
{{- end -}}
